import './globals.css';
import { Toaster } from 'react-hot-toast';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import SessionProviderWrapper from '@/components/SessionProviderWrapper'; // ✅ import Client wrapper

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Your App Name',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProviderWrapper>
          <Toaster position="top-right" />
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
